test_copen
opening handle
reading
1
properly failed
POLL 0
KILLED WITH None
POLL 1
KILLED WITH 15
Error in child process:

Traceback (most recent call last):
  File "Bio/MultiProc/copen.py", line 71, in copen_fn
    output = apply(func, args, keywords)
  File "/Users/jchang/remotecvs/biopython/Tests/test_copen.py", line 54, in raise_error
    raise AssertionError, "raised"
AssertionError: raised

